qcacld-3.0: wma_frame_inject(fix): error: mixing declarations and code
This commit fixes the following error introduced through commit 64eb391

error: mixing declarations and code is a C99 extension [-Werror,-Wdeclaration-after-statement]
        struct wma_injection_queue_ctx *ctx = &g_wma_injection_ctx;

Signed-off-by: nullptr-t-oss <nullptr.oss@gmail.com>