wlan: platform: fix missing prototype errors
this commit fixes the following errors:
  error: no previous prototype for function 'oplus_conn_get_local_seconds' [-Werror,-Wmissing-prototypes]
  error: no previous prototype for function 'icnss_show_cnss_debug' [-Werror,-Wmissing-prototypes]
  error: no previous prototype for function 'oplus_free_cnss_error_logs' [-Werror,-Wmissing-prototypes]
  ...

Change-Id: Ib3d7a50fad4b343775d8cda7878a04f67a62a9eb
Signed-off-by: nullptr_t <nullptr.oss@gmail.com>