camera-kernel: fix too many args to function call
this commit fixes the following error:
  error: too many arguments to function call, expected single argument 'io_info', have 13 arguments

note: we can use cam_isp_add_io_buffers_crow instead when
      OPLUS_FEATURE_CAMERA_COMMON is defined

      todo: keep original as is and add _crow postfix to the modified
            functions only

            affected files: cam_isp_packet_parser.h
                            cam_isp_packet_parser.c
                            cam_tfe_hw_mgr.c
                            cam_ife_hw_mgr.c

Change-Id: I80b6a3ab7705cd62ba44fbd6b23e1e2290b18362
Signed-off-by: nullptr_t <nullptr.oss@gmail.com>