wlan: hal: be: include hal_be_api_mon.h for tx monitor types
hal_be_generic_api.h uses struct hal_tx_ppdu_info, struct
hal_tx_status_info, and macros TXMON_HAL / TXMON_HAL_STATUS which are
all defined in hal_be_api_mon.h, but that header was never included.
This causes build errors:

  error: declaration of 'struct hal_tx_ppdu_info' will not be visible
         outside of this function [-Werror,-Wvisibility]
  error: incomplete definition of type 'struct hal_tx_ppdu_info'
  error: implicit declaration of function 'TXMON_HAL'
  error: implicit declaration of function 'TXMON_HAL_STATUS'

Add the missing include.

Signed-off-by: nullptr-t-oss <127822226+nullptr-t-oss@users.noreply.github.com>