display-drivers: fix errors introduced from  merge
this commit fixes the following error:
  error: #else after #else
  error: use of undeclared identifier 'PANEL_REGS_CHECK_NUM_MAX'
  error: implicit declaration of function 'dsi_display_override_dma_cmd_trig'
  error: implicit declaration of function 'dsi_ctrl_override_dma_cmd_trig'

Change-Id: I02a8708c00b7fc07fe18a8dcd81bdceb077ad4d5
Signed-off-by: nullptr_t <nullptr.oss@gmail.com>