display-drivers: add missing dma_cmd_trigger enum
this commit fixes the following error:
  error: no member named 'force_dma_cmd_trigger' in 'struct dsi_host_common_cfg'

this was most likely added by oplus to give it higher prio over dma_cmd_trigger
in `dsi_ctrl_hw_cmn_init_cmddma_trig_ctrl` in dsi_ctrl_hw_cmn

Change-Id: I460429c133238fdc71c98990e16648aa14d6163e
Signed-off-by: nullptr_t <nullptr.oss@gmail.com>