camera-kernel: fix bugs introduced during merge
this commit fixes the following error:
  error: use of undeclared identifier 'got'

Change-Id: I05683eaaa7a885f2b4e1ea5c1bd2430126ad66f7
Signed-off-by: nullptr_t <nullptr.oss@gmail.com>